apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata: 
  name: metering-subscription
  namespace: metering
specs: 
  channel: stable
  name: metering-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
